#!/bin/bash
#TODO: check distro and packages

cmake . || exit 1

if ! hash patchelf 2>/dev/null; then
    echo -e "\\e[31mYou need to install the \"patchelf\" command!\nUse your package manager to install it, or get source here:\nhttps://github.com/NixOS/patchelf\\e[0m"
    exit 1
fi
BUILD_ID=$(< /dev/urandom tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)

# Change line 8 in "src/Fuzion.cpp" so it has the BUILD_ID.
awk -v BUILD_ID="$BUILD_ID" \
'NR==8 { $0 = "char Fuzion::buildID[33] = \""BUILD_ID"\"; // Line defined by the build script." } 1' \
src/Fuzion.cpp > "/tmp/$BUILD_ID"
cat "/tmp/$BUILD_ID" > src/Fuzion.cpp
rm "/tmp/$BUILD_ID"

make -j"$(grep -c "^processor" /proc/cpuinfo)" "$@" || exit 1

if [ -f build_id ]; then
    filename=$(cat build_id)
    rm "$filename"
    if [ -f /"$filename" ]; then
        sudo rm /"$filename"
    fi
    chmod 660 build_id
    mv build_id build_id_old
fi

echo "$BUILD_ID" > build_id
mv libFuzion.so "$BUILD_ID"

strip -s -v "$BUILD_ID"
patchelf --set-soname "$BUILD_ID" "$BUILD_ID" || echo -e "\\e[33mWarning: your patchelf version does not support \"--set-soname\"\nConsider building from source: https://github.com/NixOS/patchelf\\e[0m"

chmod 400 build_id # Make the build_id read-only for safety.

echo "Build Completed."
