#!/bin/sh

if grep -q libSupreme.so /proc/$(pidof csgo_linux64)/maps; then
sudo gdb -n -q -batch \
    -ex "attach $(pidof csgo_linux64)" \
    -ex "set \$dlopen = (void*(*)(char*, int)) dlopen" \
    -ex "set \$dlclose = (int(*)(void*)) dlclose" \
    -ex "set \$library = \$dlopen(\"$(pwd)/libSupreme.so\", 6)" \
    -ex "call \$dlclose(\$library)" \
    -ex "call \$dlclose(\$library)" \
    -ex "detach" \
    -ex "quit"
fi
