#!/bin/sh

/bin/echo -e "\e[31mThis script will soon be deprecated. Use ./aimtux.sh uload instead.\e[0m"
sleep 6s

#Credit: Aixxe @ aixxe.net
if grep -q libAimTux.so /proc/$(pidof csgo_linux64)/maps; then
sudo gdb -n -q -batch \
    -ex "attach $(pidof csgo_linux64)" \
    -ex "set \$dlopen = (void*(*)(char*, int)) dlopen" \
    -ex "set \$dlclose = (int(*)(void*)) dlclose" \
    -ex "set \$library = \$dlopen(\"$(pwd)/libAimTux.so\", 6)" \
    -ex "call \$dlclose(\$library)" \
    -ex "call \$dlclose(\$library)" \
    -ex "detach" \
    -ex "quit"
fi
