#!/bin/bash

if [ ! -d ".git" ]; then
    read -p "This will delete local code changes. Are you sure? (y/n)" -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]
    then
        git reset --hard
        ./update
    fi
else
    echo "Not a git repository (or any of the parent directories): .git. Do NOT download the repository as a zip file from GitHub.com! Please download Fuzion by cloning the Git repository: 'git clone --recursive https://github.com/LWSS/Fuzion.git'"
    exit
fi
