#!/bin/bash
if [ ! -d ".git" ]; then
    echo ".git folder missing. Please re-download AimTux-Fuzion with the command 'git clone --recursive https://github.com/LWSS/AimTux.git' into a new folder."
    exit
else
    git pull
    git submodule update --init --recursive --remote
    cmake .
    make -j$(grep "^processor" /proc/cpuinfo | wc -l) "$@"
fi
