#!/bin/sh

if [ ! -d ".git" ]; then
	echo "You have downloaded aimtux-master.zip from the GitHub website. This is the WRONG way to download AimTux. Please download AimTux with the command 'git clone https://github.com/McSwaggens/AimTux.git'"
	exit
fi

git pull
cmake .
make -j$(cat /proc/cpuinfo | grep "^processor" | wc -l) "$@"
